services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app
    command: sh -c "npm run db:migrate && npm run dev:docker"
    env_file:
      - .env.docker
    environment:
      - NODE_ENV=development
      - 'TBANK_PASSWORD_FILE=tbank-password.txt'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - app_data:/app/data
    ports:
      - "8080:8080"

volumes:
  app_data:
